### PR TITLE
Removed comments

### PR DESCRIPTION
**Pull request by Libbna**

### CODE REVIEW

**Review by vbadkar — CHANGES_REQUESTED** [review]
There is a typo on line number 337

**Comment by Libbna** [comment]
@vbadkar  can you tell me where is a typo error?

**Comment by Libbna** [comment]
cd488854b87769f8a46353c5166b5104b4d95acb: I have made the changes as you requested. Please review it and let me know.

**Review by vbadkar — CHANGES_REQUESTED** [review]
Can you remove the header file? as it will change the base tag on my local too and the code won't work for me then

**Comment by Libbna** [comment]
a1c9fa4: I have removed the header file. Can you review the changes?

**Pull request merged**
